namespace PsychoGarden.Utils
{
    public enum LineColor
    {
        White,
        Black,
        Gray,
        LightGray,
        DarkGray,
        Red,
        LightRed,
        DarkRed,
        Green,
        LightGreen,
        DarkGreen,
        Blue,
        LightBlue,
        DarkBlue,
        Cyan,
        LightCyan,
        DarkCyan,
        Magenta,
        LightMagenta,
        DarkMagenta,
        Yellow,
        LightYellow,
        DarkYellow,
        Orange,
        LightOrange,
        DarkOrange,
        Brown,
        Pink,
        Purple,
        Teal,
        Lime,
        Indigo,
        Gold,
        Silver
    }

}
